version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ~/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "mail@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "9000:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    command: --auth admin
    command: --serviceExecutor adaptive
    volumes:
      - ./mongo:/data/db
    networks:
      - stack

  mongo-visualizer:
    container_name: mongo-admin
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://username:password@localhost:27017/db?ssl=false
    depends_on:
      - mongo
    networks:
      - stack
  
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./data:/home/docker/data"
    networks:
      - stack
  
  redis-visualizer:
    container_name: redis-admin
    image: marian/rebrow
    links:
      - redis:redis
    ports:
      - "8080:5001"
    networks:
      - stack

networks:
  stack:
    name: stack
    driver: bridge
  postgres-network:
    name: postgres-network
    driver: bridge
